### PR TITLE
PLANET-5724: Automatic redirection based on cookie

### PR DESCRIPTION
**Pull request by lithrel**
Ref: https://jira.greenpeace.org/browse/PLANET-5274

> Back in PLANET-3329 we add a new cookie variable to store the last visited NRO website.  
Since the landing page is on the same domain with almost all the NRO websites, it can read that cookie and use its value to redirect.

This PR checks the content of the `gp_nro` cookie against an allow-list based on the country list we already have, and redirects if an NRO url matches.

~~https://user-images.githubusercontent.com/617346/87049392-35b28500-c1fd-11ea-9880-9f8d3f057134.png~~

Screenshot 2020-07-10 at 14 32 32

## Allow list

The list is generated by `urls()` at build during `gulp countries`, to avoid doing this calculation for every visit. It is using the resulting list of NROs given by `countries()`.

## Redirection

- Cookie content and URL are verified as much as possible to avoid unexpected behavior. 
- A link to the expected redirection is still available, in case the redirection fails for some reason.

## Testing

- Follow the extensive [readme directions](https://github.com/greenpeace/planet4-landing-page#run-locally) to run the site locally
- Add a cookie on localhost with a string `gp_nro = https://www.greenpeace.org/finland` (you can type in the console `document.cookie = 'gp_nro = https://www.greenpeace.org/finland'`)
- Visit your local website, you should be redirected to the Finland website
- Putting in the cookie any URL that is not in our country list should not trigger any redirect or change in the website
- You can also play directly with `js/static/redirect.js`, the function `redirectFromCookie` accepts 2 parameters `cookie` (the cookie string) and `location` (the current url)

### Is it pretty ?
~~Hmf, you've noticed. I've used the existing classes, not sure if it fits this case.~~

#### Am I gonna get stuck in a website with a foreign language ?
Finland has a country picker just next to the title, it's ok. Luxembourg has a country picker in the footer that doesn't seem to work(?), I hope you speak french or german.

### CODE REVIEW

**Comment by comzeradd** [comment]
Functionality looks good :+1: 

Some cosmetic changes:
 - Do you think you can also get the NRO name and use that for the button? The same copy that the CTA has (see screenshot below). So it's less cryptic, but also to fit in one row.
- Maybe hide the loading spinner when we have a redirection match.


Screenshot from 2020-07-10 12-39-13

**Comment by lithrel** [comment]
NRO name added (by adding them to the generated url list), spinner hidden, two more css rules to keep a one-line button, and in case an nro name is really long for mobile 👌

**Comment by comzeradd** [comment]
I think you misspelled the ticket number in the commit message ;)  `s/5724/5274/`

**Review by comzeradd — APPROVED** [review]
:100:

**Pull request merged**
